# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Multi
version:      1.006
version_from: 
installdirs:  site
requires:
    Tie::IxHash:                   0
    Tk:                            800.013
    Tk::ObjScanner:                1.016
    Tk::Pod:                       0
    Tk::TFrame:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
